services:
  sqlbot:
    image: sqlbot:v1.0
    container_name: sqlbot
    restart: always
    privileged: true
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      POSTGRES_SERVER: pg
      POSTGRES_PORT: 5432
      POSTGRES_DB: sqlbot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password123@pg
      # ... 其他环境变量
    volumes:
      - ./data/sqlbot/excel:/opt/sqlbot/data/excel
      - ./data/sqlbot/file:/opt/sqlbot/data/file
      - ./data/sqlbot/images:/opt/sqlbot/images
      - ./data/sqlbot/logs:/opt/sqlbot/app/logs
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: pgvector/pgvector:pg17
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sqlbot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password123@pg
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d sqlbot"]
      interval: 10s
      timeout: 5s
      retries: 3